version: "3.9"
services:
  portable-playout:
    image: beamwell/portable-playout:latest
    container_name: PortablePlayout
    restart: no
    environment:
      - STREAM_URL=rtmp://your_rtmp_server:1935/live/your_stream_key
      # - PASSTHROUGH=true
      - RESOLUTION=1280x720
      - FRAME_RATE=30
      - KEYFRAME_INTERVAL=60
      - VIDEO_BITRATE=2000
      - AUDIO_BITRATE=128
      - SAMPLE_RATE=44100
    volumes:
      - ./play_me:/play_me